name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ closed ]

# Give the job the permissions it needs to push
permissions:
  contents: write       # allow pushes to repo content
  pages: write          # allow Pages publishing
  id-token: write       # sometimes required for actions that use OIDC

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js (optional, for build tools)
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Build (if needed)
      run: |
        echo "No build required for static HTML"

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        publish_branch: gh-pages
